/** Photos supplied for the Tikobane website; captions describe visible subjects. */
export const galleryCategories = [
  "Visits & Experiences",
  "Community & Learning",
  "Farming & Enterprise",
  "Wildlife & Coexistence",
  "Youth & Mentorship",
  "Landscapes & Environment",
  "Livestock & Herding",
] as const;
export type GalleryCategory = (typeof galleryCategories)[number];
export type GalleryItem = {
  id: string;
  category: GalleryCategory;
  caption: string;
  shape: "square" | "tall" | "wide";
  imageSeed: string;
  image: string;
};
export const galleryItems: GalleryItem[] = [
  {
    id: "tikobane-1",
    category: "Visits & Experiences",
    caption: "Youth group in an open safari vehicle",
    shape: "square",
    imageSeed: "youth-safari",
    image: "/images/tikobane/youth-safari.jpg",
  },
  {
    id: "tikobane-2",
    category: "Community & Learning",
    caption: "Participants talking in a thatched meeting space",
    shape: "tall",
    imageSeed: "meeting-conversations",
    image: "/images/tikobane/meeting-conversations.jpg",
  },
  {
    id: "tikobane-3",
    category: "Community & Learning",
    caption: "An outdoor interview being filmed beside a thatched building",
    shape: "square",
    imageSeed: "outdoor-interview",
    image: "/images/tikobane/outdoor-interview.jpg",
  },
  {
    id: "tikobane-4",
    category: "Farming & Enterprise",
    caption: "A sunflower in bloom",
    shape: "tall",
    imageSeed: "sunflower",
    image: "/images/tikobane/sunflower.jpg",
  },
  {
    id: "tikobane-5",
    category: "Wildlife & Coexistence",
    caption: "Young people holding a human-wildlife coexistence banner",
    shape: "square",
    imageSeed: "youth-coexistence",
    image: "/images/tikobane/youth-coexistence.jpg",
  },
  {
    id: "tikobane-6",
    category: "Community & Learning",
    caption: "Community members seated beside packaged supplies",
    shape: "square",
    imageSeed: "community-supplies",
    image: "/images/tikobane/community-supplies.jpg",
  },
  {
    id: "tikobane-7",
    category: "Youth & Mentorship",
    caption: "Youth group standing outside a thatched building",
    shape: "square",
    imageSeed: "youth-group",
    image: "/images/tikobane/youth-group.jpg",
  },
  {
    id: "tikobane-8",
    category: "Visits & Experiences",
    caption: "A group discussion outside a thatched building",
    shape: "square",
    imageSeed: "visitor-discussion",
    image: "/images/tikobane/visitor-discussion.jpg",
  },
  {
    id: "tikobane-9",
    category: "Youth & Mentorship",
    caption: "Young people standing together in a circle",
    shape: "square",
    imageSeed: "youth-circle",
    image: "/images/tikobane/youth-circle.jpg",
  },
  {
    id: "tikobane-10",
    category: "Wildlife & Coexistence",
    caption: "Elephants gathered on open grassland",
    shape: "tall",
    imageSeed: "elephants-grassland",
    image: "/images/tikobane/elephants-grassland.jpg",
  },
  {
    id: "tikobane-11",
    category: "Wildlife & Coexistence",
    caption: "A participant watching an elephant from a viewing area",
    shape: "wide",
    imageSeed: "elephant-observation",
    image: "/images/tikobane/elephant-observation.jpg",
  },
  {
    id: "tikobane-12",
    category: "Wildlife & Coexistence",
    caption: "A tree with broken branches beside a field",
    shape: "square",
    imageSeed: "broken-tree",
    image: "/images/tikobane/broken-tree.jpg",
  },
  {
    id: "tikobane-13",
    category: "Community & Learning",
    caption: "Community members gathered under an open shelter",
    shape: "square",
    imageSeed: "community-meeting",
    image: "/images/tikobane/community-meeting.jpg",
  },
  {
    id: "tikobane-14",
    category: "Landscapes & Environment",
    caption: "Discarded litter on open ground",
    shape: "square",
    imageSeed: "environmental-litter",
    image: "/images/tikobane/environmental-litter.jpg",
  },
  {
    id: "tikobane-15",
    category: "Community & Learning",
    caption: "Participants attending an indoor presentation",
    shape: "square",
    imageSeed: "indoor-presentation",
    image: "/images/tikobane/indoor-presentation.jpg",
  },
  {
    id: "tikobane-16",
    category: "Youth & Mentorship",
    caption: "Children and adults taking part in an outdoor activity",
    shape: "wide",
    imageSeed: "outdoor-activity",
    image: "/images/tikobane/outdoor-activity.jpg",
  },
  {
    id: "tikobane-17",
    category: "Landscapes & Environment",
    caption: "A branching tree overlooking open grassland",
    shape: "square",
    imageSeed: "grassland-tree",
    image: "/images/tikobane/grassland-tree.jpg",
  },
  {
    id: "tikobane-18",
    category: "Visits & Experiences",
    caption: "A safari vehicle crossing open grassland",
    shape: "square",
    imageSeed: "safari-landscape",
    image: "/images/tikobane/safari-landscape.jpg",
  },
  {
    id: "tikobane-19",
    category: "Landscapes & Environment",
    caption: "Clouds over the landscape at dusk",
    shape: "square",
    imageSeed: "landscape-dusk",
    image: "/images/tikobane/landscape-dusk.jpg",
  },
  {
    id: "tikobane-20",
    category: "Youth & Mentorship",
    caption: "A group seated in an outdoor discussion circle",
    shape: "square",
    imageSeed: "outdoor-learning",
    image: "/images/tikobane/outdoor-learning.jpg",
  },
  {
    id: "tikobane-21",
    category: "Visits & Experiences",
    caption: "Participants examining an item together outdoors",
    shape: "square",
    imageSeed: "shared-discovery",
    image: "/images/tikobane/shared-discovery.jpg",
  },
  {
    id: "tikobane-22",
    category: "Landscapes & Environment",
    caption: "An orange evening sky over water",
    shape: "square",
    imageSeed: "evening-water",
    image: "/images/tikobane/evening-water.jpg",
  },
  {
    id: "tikobane-23",
    category: "Landscapes & Environment",
    caption: "Sunset over water framed by a tree",
    shape: "square",
    imageSeed: "sunset-tree",
    image: "/images/tikobane/sunset-tree.jpg",
  },
  {
    id: "tikobane-24",
    category: "Community & Learning",
    caption: "Participants seated in a circle inside a meeting space",
    shape: "wide",
    imageSeed: "group-workshop",
    image: "/images/tikobane/group-workshop.jpg",
  },
  {
    id: "tikobane-25",
    category: "Farming & Enterprise",
    caption: "Hands holding a woven basket and weaving materials",
    shape: "square",
    imageSeed: "basket-weaving",
    image: "/images/tikobane/basket-weaving.jpg",
  },
  {
    id: "tikobane-26",
    category: "Wildlife & Coexistence",
    caption: "A group displaying a peaceful coexistence banner",
    shape: "square",
    imageSeed: "coexistence-banner",
    image: "/images/tikobane/coexistence-banner.jpg",
  },
  {
    id: "tikobane-27",
    category: "Visits & Experiences",
    caption: "Young people visiting an outdoor display beneath trees",
    shape: "square",
    imageSeed: "youth-visit",
    image: "/images/tikobane/youth-visit.jpg",
  },
  {
    id: "tikobane-28",
    category: "Visits & Experiences",
    caption: "A swimming pool surrounded by trees",
    shape: "square",
    imageSeed: "garden-pool",
    image: "/images/tikobane/garden-pool.jpg",
  },
  {
    id: "tikobane-29",
    category: "Wildlife & Coexistence",
    caption:
      "Community members displaying solar equipment and coexistence materials",
    shape: "square",
    imageSeed: "community-equipment",
    image: "/images/tikobane/community-equipment.jpg",
  },
  {
    id: "tikobane-30",
    category: "Wildlife & Coexistence",
    caption: "Participants preparing materials beneath a coexistence banner",
    shape: "square",
    imageSeed: "coexistence-preparation",
    image: "/images/tikobane/coexistence-preparation.jpg",
  },
  {
    id: "tikobane-31",
    category: "Farming & Enterprise",
    caption: "A participant working beside a crop field and suspended bottles",
    shape: "square",
    imageSeed: "field-demonstration",
    image: "/images/tikobane/field-demonstration.jpg",
  },
  {
    id: "tikobane-32",
    category: "Wildlife & Coexistence",
    caption: "Bottles suspended along the edge of a crop field",
    shape: "square",
    imageSeed: "crop-boundary",
    image: "/images/tikobane/crop-boundary.jpg",
  },
  {
    id: "tikobane-33",
    category: "Farming & Enterprise",
    caption: "A visitor talking with a basket maker beside her woven pieces",
    shape: "square",
    imageSeed: "basket-maker-visit",
    image: "/images/tikobane/basket-maker-visit.jpg",
  },
  {
    id: "tikobane-34",
    category: "Farming & Enterprise",
    caption: "A basket maker sharing her work with a visitor",
    shape: "square",
    imageSeed: "basket-maker",
    image: "/images/tikobane/basket-maker.jpg",
  },
  {
    id: "tikobane-35",
    category: "Farming & Enterprise",
    caption: "A field of sunflowers beneath a blue sky",
    shape: "wide",
    imageSeed: "sunflower-field",
    image: "/images/tikobane/sunflower-field.jpg",
  },
  {
    id: "tikobane-36",
    category: "Community & Learning",
    caption: "Participants listening during an outdoor discussion",
    shape: "tall",
    imageSeed: "discussion-participants",
    image: "/images/tikobane/discussion-participants.jpg",
  },
  {
    id: "tikobane-37",
    category: "Farming & Enterprise",
    caption: "A close view of a grain seed head",
    shape: "tall",
    imageSeed: "grain-crop",
    image: "/images/tikobane/grain-crop.jpg",
  },
  {
    id: "tikobane-38",
    category: "Community & Learning",
    caption: "A facilitator addressing participants under a shelter",
    shape: "square",
    imageSeed: "facilitated-session",
    image: "/images/tikobane/facilitated-session.jpg",
  },
  {
    id: "tikobane-39",
    category: "Community & Learning",
    caption: "A speaker leading a community discussion",
    shape: "square",
    imageSeed: "community-speaker",
    image: "/images/tikobane/community-speaker.jpg",
  },
  {
    id: "tikobane-40",
    category: "Farming & Enterprise",
    caption: "Rows of young crops beneath a cloudy sky",
    shape: "square",
    imageSeed: "young-crops",
    image: "/images/tikobane/young-crops.jpg",
  },
  {
    id: "tikobane-41",
    category: "Farming & Enterprise",
    caption: "A maize field under gathering clouds",
    shape: "square",
    imageSeed: "maize-field",
    image: "/images/tikobane/maize-field.jpg",
  },
  {
    id: "tikobane-42",
    category: "Farming & Enterprise",
    caption: "Participants displaying fruit and produce at an event",
    shape: "square",
    imageSeed: "produce-event",
    image: "/images/tikobane/produce-event.jpg",
  },
  {
    id: "tikobane-43",
    category: "Farming & Enterprise",
    caption: "Evenly spaced crop rows across a cultivated field",
    shape: "square",
    imageSeed: "crop-rows",
    image: "/images/tikobane/crop-rows.jpg",
  },
  {
    id: "tikobane-44",
    category: "Livestock & Herding",
    caption: "A farmer working a field with cattle",
    shape: "tall",
    imageSeed: "farmer-cattle",
    image: "/images/tikobane/farmer-cattle.jpg",
  },
  {
    id: "tikobane-45",
    category: "Community & Learning",
    caption: "Community members gathered with programme banners",
    shape: "square",
    imageSeed: "community-gathering",
    image: "/images/tikobane/community-gathering.jpg",
  },
  {
    id: "tikobane-46",
    category: "Livestock & Herding",
    caption: "A group gathered around a goat in a livestock enclosure",
    shape: "square",
    imageSeed: "livestock-session",
    image: "/images/tikobane/livestock-session.jpg",
  },
  {
    id: "tikobane-47",
    category: "Farming & Enterprise",
    caption: "Two participants behind a display of fruit, roots and seeds",
    shape: "square",
    imageSeed: "produce-display",
    image: "/images/tikobane/produce-display.jpg",
  },
  {
    id: "tikobane-48",
    category: "Livestock & Herding",
    caption: "Two participants beside a cattle enclosure and water trough",
    shape: "square",
    imageSeed: "cattle-enclosure",
    image: "/images/tikobane/cattle-enclosure.jpg",
  },
  {
    id: "tikobane-49",
    category: "Community & Learning",
    caption: "An outdoor presentation beneath a leafy tree",
    shape: "square",
    imageSeed: "tree-presentation",
    image: "/images/tikobane/tree-presentation.jpg",
  },
  {
    id: "tikobane-50",
    category: "Community & Learning",
    caption: "Community members attending a session beneath a tree",
    shape: "square",
    imageSeed: "outdoor-session",
    image: "/images/tikobane/outdoor-session.jpg",
  },
  {
    id: "tikobane-51",
    category: "Livestock & Herding",
    caption: "Participants handling goats in a livestock enclosure",
    shape: "square",
    imageSeed: "goat-enterprise",
    image: "/images/tikobane/goat-enterprise.jpg",
  },
];
